version: '3.8'

services:
  app:
    image: ghcr.io/tolgaguensal-lab/stickwerk-studio:latest
    container_name: stickwerk-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=production
      - DATABASE_URL=postgresql://stickwerk_user:stickwerk_password@db:5432/stickwerk_db
      - NEXTAUTH_SECRET=stickwerk_secret_key_2026_change_me
    depends_on:
      - db
    restart: always
    volumes:
      - /DATA/AppData/stickwerk-studio/config:/app/config

  db:
    image: postgres:15-alpine
    container_name: stickwerk-db
    environment:
      - POSTGRES_USER=stickwerk_user
      - POSTGRES_PASSWORD=stickwerk_password
      - POSTGRES_DB=stickwerk_db
    volumes:
      - /DATA/AppData/stickwerk-studio/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
